#
# This Makefile was generated by Code::Blocks IDE.
#

SRCS_f95d1 = \
binsearch.f95 \
main.f95 

OBJS_f95d1 = \
binsearch.o \
main.o 

SRC_DIR_f95d1 = 
OBJS_DIR = obj/Debug/
EXE_DIR = bin/Debug/

EXE = Prime.exe
FC = mingw32-gfortran.exe
LD = mingw32-gfortran.exe
IDIR = 
CFLAGS = -Wall -g -fdefault-integer-8 -fdefault-double-8 -fdefault-real-8 -fdefault-integer-8  -J$(OBJS_DIR) $(IDIR)
LFLAGS = 
LIBS = 

VPATH = $(SRC_DIR_f95d1):$(OBJS_DIR)
OBJS = $(addprefix $(OBJS_DIR), $(OBJS_f95d1))

all : $(EXE)

$(EXE) : $(OBJS_f95d1)
	@mkdir -p $(EXE_DIR)
	$(LD) -o $(EXE_DIR)$(EXE) $(OBJS) $(LFLAGS) $(LIBS)

$(OBJS_f95d1):
	@mkdir -p $(OBJS_DIR)
	$(FC) $(CFLAGS) -c $(SRC_DIR_f95d1)$(@:.o=.f95) -o $(OBJS_DIR)$@

clean :
	rm -f $(OBJS_DIR)*.*
	rm -f $(EXE_DIR)$(EXE)

# Dependencies of files
binsearch.o: \
    binsearch.f95
main.o: \
    main.f95 \
    binsearch.o

